name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: portfolio-react
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cahce: 'npm'
    - run: npm ci
    - run: npm run build
      env:
         CI: false
    
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
